services:
  # --- NEXT.JS WEB APP ---
  - type: web
    name: nextjs-web
    env: docker
    plan: free
    dockerContext: ./apps/web
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MODE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
    healthCheckPath: /

databases:
  # --- MANAGED POSTGRES DATABASE ---
  - name: postgres-db
    plan: free
